"""Generated from org describe: permissionable standard fields plus the pre-existing External_ID__c."""
EDU_STANDARD_FIELDS = {
    "Learning": ["AcademicLevel","ActiveFromDate","ActiveToDate","Category","CipCode","Description","Duration","DurationUnit","External_ID__c","Format","Grade","ImageUrl","IsActive","ProviderId","Type"],
    "LearningCourse": ["AcademicLevel","ActiveFromDate","ActiveToDate","CipCode","CourseLevelDescription","CourseNumber","CourseType","Description","Duration","DurationUnit","External_ID__c","FieldOfStudy","IsActive","IsLinkedOnly","Product2Id","ProviderId","SubjectAbbreviation"],
    "LearningProgram": ["AcademicLevel","ActiveFromDate","ActiveToDate","Category","CipCode","Description","DoesCreateOpportunityRecord","DoesGroupOpportunities","Duration","DurationUnit","External_ID__c","Format","Grade","ImageUrl","IsActive","IsTopLevelProgram","Product2Id","ProviderId","ShortDescription"],
    "LearningProgramPlan": ["ActiveFromDate","ActiveToDate","Description","External_ID__c","IsActive","MinimumProgramGradePointAvg","ProviderId","VersionNumber"],
    "IndividualApplication": ["AcademicTerm","ApplicantEmail","ApplicantPhone","ContactId","DecisionReleaseDate","DueDate","InternalStatus","IsOwnerEditable","IsSubmitted","LearningProgram","OpportunityId","ProgramTermApplnTimelineId"],
    "ContactContactRelation": ["EndDate","IsActive","StartDate"],
    "CourseOffering": ["AcademicSessionId","AvailabilityStatus","Description","EndDate","EnrollmentCapacity","External_ID__c","IsActive","IsWaitlistActive","PrimaryFacultyId","SectionNumber","StartDate","WaitlistCapacity","WaitlistStatus"],
    "CourseOfferingParticipant": ["AcademicTermEnrollmentId","AddedToWaitlist","DroppedDateTime","EndDate","EnrollmentOfferDeclined","EnrollmentOfferExpiration","External_ID__c","IsRepeatAttempt","ParticipantAccountId","ParticipantAffiliation","ParticipationStatus","RegistrationDateTime","StartDate","Summary","WaitlistScore"],
    "CourseOfferingSchedule": ["CourseOfferingScheduleTmplId","EndDate","EndTime","External_ID__c","IsFriday","IsMonday","IsSaturday","IsSunday","IsThursday","IsTuesday","IsWednesday","LocationId","RecurrencePattern","StartDate","StartTime","Type"],
    "AcademicTerm": ["AcademicYearId","Description","EndDate","External_ID__c","IsActive","LateRegistrationDate","RegistrationCloseDate","RegistrationOpenDate","Season","StartDate"],
    "AcademicSession": ["AcademicTermId","AddDropDeadline","AuditDueDate","ClassEndDate","ClassStartDate","CourseWithdrawDeadline","Description","ExamEndDate","ExamStartDate","External_ID__c","IsActive","ResultAvailabilityDate","ResultDueDate","Season","Type"],
    "LearnerProfile": ["AcademicLevel","AcademicStanding","AcademicTermEnrollmentId","AdmitTerm","College","Concentration","ContactProfileId","CumulativeGpa","Email","EnrollmentReason","EnrollmentStatus","ExpectedGraduationDate","Gender","HasParentalFerpa","HasThirdPartyFerpa","InstructionMode","IsAthlete","IsCampusResident","IsDeceased","IsEnrolledInCareerServices","IsEnrolledInDualDegree","IsFirstGenerationStudent","IsInternationalStudent","IsPellGrantEligible","IsTransferStudent","Major","MajorDeclarationTerm","MatriculationTerm","Minor","PrimaryAdvisorId","PrimaryAdvisorName","Pronouns","SecondConcentration","SecondMajor","SecondMinor","SecondaryAdvisorId","SecondaryAdvisorName","StudentIdNumber","StudyYearClassification","TotalUnitsCompleted"],
    "DocumentChecklistItem": ["AccountId","ExtractedData","Instruction","IsAccepted","IsFrozen","IsRequired","RejectReason","RejectReasonType","UploadedById"],
}
